# -*- coding: utf-8 -*-
"""Queue__Enqueue_Dequeue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVrlogFem307YmcHNbypsEiW10PvH6di
"""

class Queue:
  def __init__(self):
    self.queue=[]
  
  def isEmpty(self):
    if self.queue==[]:
      print("EMPTY QUEUE")
    else:
      print("NOT EMPTY")

  def enqueue(self,element):
    self.queue.insert(0,element)

  def dequeue(self):
    self.queue.pop()

  def size(self):
    print("Size of Queue is: ",len(self.queue))

A=Queue()
A.isEmpty()
A.enqueue("Hello")
A.enqueue("Humans")
A.enqueue("!!!!!!")
print(A.queue)
A.dequeue()
A.isEmpty()
A.dequeue()
A.isEmpty()
A.size()