# -*- coding: utf-8 -*-
"""Stack__Using_Single_Queue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZOH0gr9_wx1M17DuXjnd0eUHjdR1eHhg
"""

class Stack_Using_Queue:
  def __init__(self):
    self.queue=[]
  
  def isEmpty(self):
    if self.queue==[]:
      print("EMPTY QUEUE")
    else:
      print("NOT EMPTY")

  def enqueue(self,element):
    self.queue.insert(0,element)

  def dequeue(self):
    return self.queue.pop()

  def size(self):
    print("Size of Queue is: ",len(self.queue))

  def pop(self):
    for i in range(len(self.queue)-1):
      x=self.dequeue()
      print(x)
      self.enqueue(x)
    print("REMOVED ELEMENT IS: ",self.dequeue())

A=Stack_Using_Queue()
A.isEmpty()
A.enqueue(1)
A.enqueue(2)
A.enqueue(3)
A.enqueue(4)
print(A.queue)
A.pop()
print(A.queue)
A.dequeue()
print(A.queue)