# -*- coding: utf-8 -*-
"""Stack__Push_Pop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4hfBcZNX0lxv3utQ3F7vajMGMDFOzHW
"""

class Stack:
  def __init__(self,n):
    self.stack=[]
    self.size=n

  def push(self,element):
    if (len(self.stack) == self.size):
      printf("STACK IS FULL")
    else:
      self.stack.append(element)

  def pop(self):
    if (len(self.stack) == 0):  #or self.stack==[]
      printf("STACK IS EMPTY")
    else:
      return self.stack.pop()

A=Stack(3)
A.push(6)
A.push(2)
print(A.stack)
A.pop()
print(A.stack)