# -*- coding: utf-8 -*-
"""Searching__SequentialSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_kOEy88m4bS_HijcZcccmvNWE9upECE
"""

def sequential_search(A,key):
  flag=0
  index=0
  for i in range(len(A)):
    if key==A[i]:
      flag=1
      index=i
      break
  if flag==0:
    print("Key not found.")
  else:
    print("Key found at index {}".format(index))

A=list(map(int,input("Enter list in sorted order: ").split(' ')))
key=int(input("Enter the key: "))
sequential_search(A,key)