# -*- coding: utf-8 -*-
"""Searching__BinarySearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f0nyckF592tsMV-RMV7g6jcojsUp7uA_
"""

def binary_search(A,key,start,end):
  mid=(start+end)//2
  flag=0
  if key>A[mid] and start<mid<end:
    binary_search(A,key,mid,end)
  elif key<A[mid] and start<mid<end:
    binary_search(A,key,start,mid)
  elif key==A[mid]:
    print("Number found at index {}".format(mid))
    flag=1
    return
  elif flag==0:
    print("Key not found")

A=list(map(int,input("Enter list in sorted order: ").split(' ')))
key=int(input("Enter the key: "))
binary_search(A,key,0,len(A))