# -*- coding: utf-8 -*-
"""Sorting__QuickSort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VWCXaKyqaUR_dnESxj0AfDmkvzWVB9CS
"""

def partition(A,l,r):
  pivot=A[r]
  i=l-1
  for j in range(l,r):
    if A[j]<=pivot:
      i+=1
      A[i],A[j]=A[j],A[i]
  A[i+1],A[r]=A[r],A[i+1]
  return i+1

def quick_sort(A,l,r):
  if len(A) == 1:
    return A
  if l<r:
    q=partition(A,l,r)
    quick_sort(A,l,q-1)
    quick_sort(A,q+1,r)

A=list(map(int,input("Enter List: ").split(' ')))
quick_sort(A,0,len(A)-1)
A