# -*- coding: utf-8 -*-
"""Sorting__SelectionSort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qM_HQ-qkDvSTy35vqk2OuK9sfOJ5EeGu

***SELECTION SORT:***


1.   Scan the list. Find the minimum element.
2.   Swap the minimum element with the value in the first position.
3.   Swap the second minimum element to second position.
4.   Repeat till the complete list is sorted.

*Time Complexity=O(n^2)*

*Space Complexity=O(1)*
"""

def selection_sort(A):
  for i in range(len(A)-1):
    minpos=i
    for j in range(i+1,len(A)):
      if A[j]<A[minpos]:
        minpos=j
    (A[i],A[minpos])=(A[minpos],A[i])
  print(A)

def selection_sort1(A):
  for i in range(len(A)-1):
    for j in range(i+1,len(A)):
      if A[j]<A[i]:
        temp=A[j]
        A[j]=A[i]
        A[i]=temp
  print(A)

A=[5,4,3,2,1]
print(A)
selection_sort1(A)