# -*- coding: utf-8 -*-
"""Arrays__Rotate(90deg)_2D_Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xUrgQI4xn-KSdsTm9PKFbJfPwrKb7iKd

Rotate(90deg) 2D martix of nxn without using extra space.

Example 1:

*INPUT*:

A=[56,96,91,54]

*OUTPUT*:

[91,56,54,96]

Example 2:

*INPUT*:

A=[1,2,3,4,5,6,7,8,9]

*OUTPUT*:

[7,4,1,8,5,2,9,6,3]
"""

def rotate(A,n):
  m=n*n
  for i in range(n):
    for j in range(i+1,n):
      A[i][j],A[j][i]=A[j][i],A[i][j]
  print("Transpose: ",A)

  for i in range(n):
    for j in range(n):
      k=abs(j-(n-1))
      if (k>j):
        A[i][j],A[i][k]=A[i][k],A[i][j]
  print("Rotate: ",A)

print("Enter the size of array: ")
n=int(input())
print("Enter the input matrix: ")
matrix=[]
for i in range(n):
  a=[]
  for j in range(n):
    a.append(int(input()))
  matrix.append(a)
# matrix = [[int(input()) for x in range (n)] for y in range(n)] 
print(matrix)
rotate(matrix,n)
