# -*- coding: utf-8 -*-
"""Arrays__MaxIn_StructArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDewHcbDh2vptzZpuK9vnuJ7V8GN4Gsw

Maximum in Struct Array.

Structure array of type height=feet,inch. Find maximum height. Convert feet to inches first.

Example 1:

*INPUT:*

N=2

H=1,2,2,1

*OUTPUT:*

25

Example 2:

*INPUT:*

N=4

H=3,5,7,9,5,6,5,6

*OUTPUT:*

93
"""

class heightComp:
  def __init__(self):
    self.N=int(input("Enter the number of cases: "))
    print("Enter Feet-inch Pairs: ")
    self.A=list(map(int,input().split(' ')))

  def compare(self):
    max=0
    for i in range(0,len(self.A),2):
      if (12*self.A[i]+A[i+1]>max):
        max=12*self.A[i]+A[i+1]
    print(max)

class heightComp2:
  def __init__(self):
    self.N=int(input("Enter the number of cases: "))
    print("Enter Feet-inch Pairs: ")

    self.structArr=[]
    for i in range(N):
      self.A=[]
      self.A=list(map(int,input().split(' ')[:2]))
      self.structArr.append(self.A)

  def compare(self):
    max=0
    for i in range(len(self.structArr)):
      if (12*self.structArr[i][0]+self.structArr[i][1]>max):
        max=12*self.structArr[i][0]+self.structArr[i][1]
    print(max)

H=heightComp2()
H.compare()