# -*- coding: utf-8 -*-
"""Arrays__Greater_on_Right.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBYSusQMNbdtX9pS9RXnLtHCwNAi1MhG

Replace every element with the next greatest element on right side. For the last element replace with -1.

Example 1:

*INPUT:*

16,17,4,3,5,2

*OUTPUT:*

17,5,5,5,2,-1

Example 2:

*INPUT:*

2,3,1,9

*OUTPUT:*

9,9,9,-1
"""

def greater_right(A):
  n=len(A)
  C=[]
  for i in range(n):
    if i<n-1:
      max=max_ele(A[i+1:n])
      A[i]=max
    else:
      A[i]=-1
  print(A)

def max_ele(A):
  n=len(A)
  max=A[0]
  for i in range(1,n):
    if A[i]>max:
      max=A[i]
  return max

print("Enter the array Elements:")
A=list(map(int,input().split(' ')))
print(A)
greater_right(A)