# -*- coding: utf-8 -*-
"""Missing_no_in_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPFB8EejLcwHGwh9wc0Y7IuQhuziPWcL

Print the missing number in an array containing numbers from 1 to n in unsorted order.
#EXAMPLE:
*INPUT*:

n=4

A=[1,3,4]

*OUTPUT*:

[3]
"""

print('Enter the size of array')
n=int(input())
print('Enter the array elements')
A=list(map(int, input().split(' ')[:n-1]))
print(A)

A.sort()
A.append(n+1)   #Alternatively: A.append(0)

for i in range(n):
  if A[i]!=(i+1):
    print(i+1)
    break
