# -*- coding: utf-8 -*-
"""Arrays__Rotate_ele_by_d(clw).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q7izIPOVHW1mVJdifgNP9RV0L6qpj8vM

Rotate the elements in an 'n' sized array by 'd' elements in clockwise direction.

*INPUT*:

d=2

n=5

A=[1,2,3,4,5]

*OUTPUT*:

[3,4,5,1,2]
"""

print("Enter 'd'(number of elements to be shifted cw)")
d=int(input())
print("Enter the size of array")
n=int(input())
print("Enter the array elements")
A=list(map(int,input().split(' ')[:n]))
print(A)

B=[]
for i in range(n):
  if i+d < n:
    B.append(A[i+d])
  else:
    B.append(A[i-(d+1)])

#Alternatively, since python has negative indexing
C=[]
for i in range(n):
  C.append(A[i-(d+1)])
