# -*- coding: utf-8 -*-
"""Arrays__MaxValue_BitonicArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btGZ-Gu03Txw-sSWqj6Vp1ZsaPv55gaq

Maximum value in bitonic array (Array elements first in increasing order than decreasing order(maybe)). Find maximum.

Example 1:

*INPUT:*

A=[1,15,25,45,42,21,17,12,11]

*OUTPUT:*

45

Example 2:

*INPUT:*

A=[1,45,47,50]

*OUTPUT:*

50
"""

def max_bitonic(A):
  n=len(A)
  max=A[0]
  for i in range(1,n):
    if (A[i]>max):
      max=A[i]
    else:
      break
  print(max)

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
max_bitonic(A)