# -*- coding: utf-8 -*-
"""Arrays__FirstNegative_InWindowK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KbL20_D9q9W-oDbgnuVxh1gHOCo2BS1

First negative integer in every window of size k.

Example 1:

*INPUT:*

A=[-8,2,3,-6,10]

K=2

*OUTPUT:*

-8,0,-6,-6

Example 2:

*INPUT:*

A=[12,-1,-7,8,-15,30,16,28]

K=3

*OUTPUT:*

-1,-1,-7,-15,-15,0
"""

def neg_win(A,k):
  n=len(A)
  B=[]
  for i in range(n-k+1):
    num=neg_num(A[i:i+k],k)
    B.append(num)
  print(B)

def neg_num(A,k):
  negative=0
  for i in range(k):
    if A[i]<negative:
      negative=A[i]
      break
  return (negative)

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
print("Enter the window value k: ")
k=int(input())
neg_win(A,k)