# -*- coding: utf-8 -*-
"""Arrays__Duplicate_ele.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YmElfvjRhzvMWrnY0g4d6-LMryo2FzU

Find duplicates in an array.

Example 1:

*INPUT*:

A=[0,1,2,3]

*OUTPUT*:

[-1]

Example 2:

*INPUT*:

A=[2,3,1,2,3]

*OUTPUT*:

[2,3]
"""

def rep_twice(A,n):
  D={}
  C=[]
  count=0
  
  for ele in A:
    try:
      D[ele] +=1
    except:
      D[ele] = 1

  for key in D:
    if (D[key]==2):
      C.append(key)
      count=count+1
  
  if count>0:
    print(C)
  else:
    C.append(-1)
    print(C)

n=int(input())
print("Enter the array elements unsorted order")
A=list((input().split(' ')[:n]))
print(A)
rep_twice(A,n)