# -*- coding: utf-8 -*-
"""Arrays__Kth_Smallest_Element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EAj_UrZpqRIAexic6CTz6Vu-R1WXs994

Given an array A, and a number k, where k is smaller than size of array. Task is to find kth smallest element in the given array.

Example 1:

*INPUT*:

n=6

A=[7,10,4,3,20,15]

k=3

*OUTPUT*:

7

Example 2:

*INPUT*:

n=5

A=[7,10,4,20,15]

k=4

*OUTPUT*:

15
"""

def kth_min(A,k):
  A.sort()
  return A[k-1]

print("Enter the Array Elements: ")
A= list(map(int,input().split(' ')))
print("Enter the 'k' value: ")
k=int(input())
element_min=kth_min(A,k)
print(element_min)