# -*- coding: utf-8 -*-
"""Arrays_OccurenceOf_X_InSortedArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15YEhbQZRwnKz9iY_xXSp-NBKtxWRvEny

Number of occurence of k in sorted array.

Example 1:

*INPUT:*

A=1,1,2,2,2,2,3

k=2

*OUTPUT:*

4

Example 2:

*INPUT:*

A=1,1,2,2,2,2,3

k=4

*OUTPUT:*

-1
"""

def occur_k(A,k):
  n=len(A)
  D={}
  for ele in A:
    try:
      D[ele]+=1
    except:
      D[ele]=1

  if k in D.keys():
    count=D[k]
    print(count)
  else:
    print("-1")

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
print("Enter the value of k: ")
k=int(input())
occur_k(A,k)