# -*- coding: utf-8 -*-
"""Arrays__Count_zeros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vex25GqyTksPiiKsb7k5l7qjGI7jCAT5

Count the number of zeros in reverse sorted array containing 0 and 1

Example 1:

*INPUT*:

n=5

A=[1,1,1,0,0]

*OUTPUT*:

2

Example 2:

*INPUT*:

n=5

A=[1,1,1,1,1]

*OUTPUT*:

0
"""

print("Enter the size of array")
n=int(input())
print("Enter the array elements (0s and 1s) in reverse sorted order")
A=list(map(int,input().split(' ')[:n]))
print(A)

p=0
for i in range(n-1,-1,-1):
  if A[i]==0:
    p=p+1
  else:
    break
print(p)