# -*- coding: utf-8 -*-
"""Arrays__Additing_Submatrix_elements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fw9wjdpXAx1UMiDjJoofu1nXY4sWfTWu

Addition of submatrix elements in a nxm matrix given (x1,y1) , (x2,y2) as the start and end index of sub matrix.

Example 1:

*INPUT*:

n=3

m=3

Matrix=
9 8 7 
4 2 1 
6 5 3

(x1,y1)= 1,2

(x2,y2)= 3,3

*OUTPUT*:

26

Example 2:

*INPUT*:

n=5

m=6

Matrix=
1 2 3 4 5 6
7 8 9 10 11 12
13 14 15 16 17 18
19 20 21 22 23 24
25 26 27 28 29 30

(x1,y1)= 3,4

(x2,y2)= 4,5

*OUTPUT*:

78
"""

def submatrix_sum(matrix,x1,y1,x2,y2):
  sum=0
  x1=x1-1
  x2=x2-1
  y1=y1-1
  y2=y2-1 #since zero indexing is used
  for i in range(x1,x2+1):
    for j in range(y1,y2+1):
      sum=sum+matrix[i][j]
  print("Sum is: ",sum)

n = int(input("Enter the number of rows:")) 
m = int(input("Enter the number of columns:"))
print("Enter the Matrix Elements: ")
matrix=[]
for i in range(n):
  a=[]
  for j in range(m):
    a.append(int(input()))
  matrix.append(a)
x1,y1= map(int, input("Enter the first index: ").split())
x2,y2= map(int, input("Enter the second index: ").split())

submatrix_sum(matrix,x1,y1,x2,y2)