# -*- coding: utf-8 -*-
"""Arrays__Transition_pt_0/1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ml3KJQ88YeFsG0fSX3q_W33q8WBanu8c

Find the transition point in an array containing sorted 0 and 1. Print -1 for all 0s or all 1s.

Example 1:

INPUT:

n=5

A=[0,0,0,1,1]

OUTPUT:

3


Example 2:

INPUT:

n=5

A=[1,1,1,1,1]

OUTPUT:

-1
"""

print("Enter the size of array")
n=int(input())
print("Enter the array elements (0s and 1s) in sorted order")
A=list(map(int,input().split(' ')[:n]))
print(A)

p=0
for i in range(n):
  if A[i]==0:
    p=p+1
  else:
    break

if p==n or p==0:
  print('-1')
else:
  print(p)