# -*- coding: utf-8 -*-
"""Arrays__Zero_Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pDqK1pml589wXGmTKaHcFRRYE5HtCQAf

If an element in an nxm matrix is zero entire row and column are set to zero.

Example:

*INPUT:*

A=

1  2  3  

4  0  6  

7  8  9

*OUTPUT:*

1  0  3

0  0  0

7  0  9
"""

def zero_mat(matrix,m,n):
  row=[]
  col=[]
  for i in range(n):
    for j in range(m):
      if (len(row)==0 or (search_ele(i,row) and search_ele(j,col))!=0): #and len(col)==0
        if matrix[i][j]==0:
          row.append(i)
          col.append(j)
          for k in range(m):
            matrix[i][k]=0
          for k in range(n):
            matrix[k][j]=0
  print(matrix)

def search_ele(ele,A):
  for i in range(len(A)):
    if ele==A[i]:
      return 1
  return 0

print("Enter the matrix size: ")
n,m=input().split(' ')
n=int(n)
m=int(m)
matrix=[]
for i in range(n):
  B=[]
  for j in range(m):
    B.append(int(input()))
  matrix.append(B)
print(matrix)
zero_mat(matrix,m,n)