# -*- coding: utf-8 -*-
"""Arrays__Multiply_2Polynomials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RuKgIZX6X01HQc6i3wr7p03nUKNE2b_m

Two polynomials are represented by two arrays containing coefficients. Print the multiplication array. m,n are the highest degree of A1,A2.

Example 1:

*INPUT:*

A1=[1,0,3,2]

A2=[2,0,4]

*OUTPUT:*

A=[2,0,10,4,12,8]

Example 2:

*INPUT:*

A1=[1,9,3,4,7]

A2=[4,0,2,5]

*OUTPUT:*

A=[4,36,14,39,79,23,34,35]
"""

def poly_mul(A1,A2):
  B=[]
  for i in range(len(A1)+len(A2)-1):
    B.append(0)
  for i in range(len(A1)):
    for j in range(len(A2)):
      B[i+j]+=(A1[i]*A2[j])
  print(B)

print("Enter the two arrays: ")
A1=list(map(int,input().split(' ')))
A2=list(map(int,input().split(' ')))
print(A1)
print(A2)
poly_mul(A1,A2)