# -*- coding: utf-8 -*-
"""Arrays__EleRepeatedTwice_exceptOne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QI4CZwueENcWo4VaBSbj8Vp97eDoBHU

There is an array with every element repeated twice except one. Find that element. Also define a function if more then one element occurs only once.

Example 1:

*INPUT*:

A=[1,1,2,2,3,4,4]

*OUTPUT*:

3

Example 2:

*INPUT*:

A=[1,1,2,3,3,4,4,5]

*OUTPUT*:

2,5
"""

def single_element(A,n):
  B=[]
  i=0
  while(i+1 < n):
    if A[i]==A[i+1]:
      i=i+2
    else:
      B.append(A[i])
      i=i+1
  if (i==n-1):
    B.append(A[n-1])

  print(B)

print("Enter the array elements sorted order")
A=list(map(int,input().split(' ')))
print(A)
n=len(A)
single_element(A,n)