# -*- coding: utf-8 -*-
"""Arrays__Index_Extra_Ele.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13foxBDmcKlhftpkl2IHK-LQ6UX58JiW_

Index of an  extra element.

Example:

*INPUT:*

A=2,4,6,8,9,10,12

B=2,4,6,8,10,12

*OUTPUT:*

4
"""

def missing_index(A,B):
  for ele in B:
    for index,elements in enumerate(A):
      if elements not in B:
        c=1
        print("Index: ",index)
    if c==1:
      break

print("Enter the two arrays: ")
A=list(map(int,input().split(' ')))
B=list(map(int,input().split(' ')))
missing_index(A,B)