# -*- coding: utf-8 -*-
"""Arrays__Count_SmallerEle_toRight.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yn0RVGLd3ZM8SEbP4HF8iusa_LyWYJzy

Count the number of smaller elements to the right.

Example 1:

*INPUT:*

A=[12,1,2,3,0,11,4]

*OUTPUT:*

[6,1,1,1,0,1,0]

Example 2:

*INPUT:*

A=[1,2,3,4,5]

*OUTPUT:*

[0,0,0,0,0]
"""

def right_count(A):
  n= len(A)
  B=[]
  for i in range(n-1):
    x=min_ele(A[i+1:n],A[i])
    B.append(x)
  B.append(0)
  print(B)

def min_ele(A,x):
  count=0
  n=len(A)
  for i in range(n):
    if A[i]<x:
      count=count+1
  return count

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
right_count(A)