# -*- coding: utf-8 -*-
"""Arrays__Element_appearing_Once.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDCLkJXhux3Sqt1xY5Lb0l0SHdKhjuXG

Print the element appering oncein a list.

Example 1:

*INPUT:*

A=[1,1,2,5,5]

*OUTPUT:*

2

Example 2:

*INPUT:*

A=[2,2,5,5,20,30,30]

*OUTPUT:*

20
"""

def element_once(A):
  n=len(A)
  D={}
  for ele in A:
    try:
      D[ele]+=1
    except:
      D[ele]=1
  for key in D.keys():
    if D[key]==1:
      print(key)

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
element_once(A)