# -*- coding: utf-8 -*-
"""Arrays__Len_NonOverlapArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzLP1SRD9WEVmGGjf1Uni3utTdSZTxl5

Sum of lengths of non overlapping arrays. "k" is the maximum sub array element.

Example 1:

*INPUT*:

n=9

A=[2,1,4,9,2,3,8,3,4]

k=4

*OUTPUT*:

SA1=[2,1,4]

SA2=[3,4]

sum=5

Example 2:

*INPUT*:

n=7

A=[1,2,3,2,3,4,1]

k=4

*OUTPUT*:

SA1=[1,2,3,2,3,4,1]

sum=7

Example 3:

*INPUT*:

n=10

A=[4,5,7,1,2,9,8,4,3,1]

k=4

*OUTPUT*:

SA1=[4]

SA2=[4,3,1]

sum=4
"""

def sub_array(A,k):
  k=int(k)
  c=0
  sum=0
  while (c<len(A)):
    SA=[]
    for i in range(len(A)):
      if ((A[i]) <= k):
        SA.append(A[i])
      else:
        sum=sum+check_four(SA)
        c=i+1
        break
  print("SUM= ",sum)

def check_four(SA):
  count=0
  for i in range(len(SA)):
    if A[i]==4:
      count=count+1
      break
  if count>0:
    return (len(SA))
  else:
    return (0)

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
k=int(input())
sub_array(A,k)