# -*- coding: utf-8 -*-
"""Arrays__sort_matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uei_sTBB_RFPYQBLV23mUbQd8k2-A4kC
"""

def sort_matrix(A,n):
  B=[]
  matrix_new=[]
  for i in range(n):
    for j in range(n):
      B.append(A[i][j])
  for i in range(n*n-1):
    for j in range(i+1,n*n):
      if (B[j]<B[i]):
        B[j],B[i]=B[i],B[j]
  print(B)

print("Enter the matrix size: ")
n=int(input())
matrix=[]
for i in range(n):
  a=[]
  for i in range(n):
    a.append(int(input()))
  matrix.append(a)
print(matrix)
sort_matrix(matrix,n)