# -*- coding: utf-8 -*-
"""BackTracking__SubsetSum_Ascending.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBbSCvz1VrOm9K-U25CIL19XmRtCTYOv

Piggy Bank.

Daniel has 2 piggy banks. A bigger oone and a smaller one. He has divided the bigger piggy bank in X slotts and the smaller on in Y slots. X>Y

He has some money deposited in both of them. he chooses Y slots from the bigger piggy bank and transfers their money to Y slots of the smaller one in respective order. He wants that the amount in slot n+1 should always be greater than or equal to that in the slot n, of the smaller piggy bank, after the transfer from the bigger piggy bank. You have to help Daniel to count the number of ways he can transfer the money.

*INPUT SPECIFICATIONS:*

*INPUT1: Number of slots in bigger piggy bank.*

*INPUT2: Number of slots in smaller piggy bank.*

*INPUT3: Amounts in slots of bigger piggy bank.*

*INPUT4: Amounts in slots of smaller piggy bank.*

*OUTPUT SPECIFICATIONS:*

*Return the number of ways to transfer amount.*

Example 1:

*INPUT:*

5

3

1,5,2,4,7

7,9,6

*OUTPUT:*

4

{(1,2,7),(1,4,7),(5,4,7),(2,4,7)}

Example 2:

*INPUT:*

4

2

7,7,7,7

3,4

*OUTPUT:*

6

{(7,7),(7,7),(7,7),(7,7),(7,7),(7,7)}

Pos:{(1,2),(1,3),(1,4),(2,3),(2,4),(3,4)}
"""

def count(a1,a2):   #len(a1)<len(a2)=n,m
  mat=[]
  for i in range(len(a1)):
    A=[]
    for j in range(len(a2)):
      A.append(a1[i]+a2[j])
    mat.append(A) #sum matrix:nxm
  print(mat)

  T=[[0 for x in range(len(a2))] for y in range(len(a1))] 
  print(T)

  #for i in range(len(a1)): 
   # T[i][0] = 1
  for j in range(len(a2)): 
    T[0][j] = 1
  print(T)

  for i in range(len(a1)):
    for j in range(len(a2)):
      for k in range(j-1,-1,-1):
        if mat[i-1][k]<=mat[i][j]:
          #print("i,j",i,j)
          #print(mat[i-1][k],mat[i][j])
          T[i][j]=T[i-1][k]+T[i][j]
          #print("T[i][j]",T[i][j])
  print(T)
  count=0
  for i in range(len(a2)):
    if T[len(a1)-1][i] >= len(a1)-1:
      count=count+T[len(a1)-1][i]
  print(count)

A=[7,9,6]
B=[1,5,2,4,7]
count(A,B)