# -*- coding: utf-8 -*-
"""BitManipulation__SetBits_Count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17GD8XzgNXCp44uGc0sFtfjpCebaxg6Mp

Set Bits.

Given N. Print count of set bits.

Example 1:

*INPUT:*

6

*OUTPUT:*

2

Example 2:

*INPUT:*

11

*OUTPUT:*

3
"""

def count_set(A):
  count=0
  while (A>0):
    x=A%2
    if x==1:
      count+=1
    A=A//2
  print(count)

print("Enter the number: ")
N=int(input())
count_set(N)