# -*- coding: utf-8 -*-
"""BitManipulation__EvenBitSetZero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vy5CcB1DP5sk6YlzGkYmglS7jLnSYX1Y

Change all even bits to zero.

Example 1:

*INPUT:*

10

*OUTPUT:*

10

Example 2:

*INPUT:*

30

*OUTPUT:*

10
"""

def even_bit(N):
  num=[]
  bin_num=[]
  pos=0
  while (N>0):
    x=N%2
    if pos%2==0:
      num.append(0)
    else:
      num.append(x)
    N=N//2
    pos+=1
  for i in range(len(num)-1,-1,-1):
    bin_num.append(num[i])
  bin_dec(bin_num)

def bin_dec(num):
  value=0
  x=len(num)-1
  for i in range(len(num)):
    value=value+(2**x)*num[i]
    x-=1
  print(value)

print("Enter the integer: ")
x=int(input())
even_bit(x)