# -*- coding: utf-8 -*-
"""BitManipulation__SwapNibbles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNe3YBYS0WOEtvMSCOXcJpBA774fltlv

Swap two nibbles in a byte.

Example:

*INPUT:*

100

*OUTPUT:*

70
"""

def swap_nibbles(N):

  bin_num=[]
  num=[]
  while (N>0):
    x=N%2
    bin_num.append(x)
    N=N//2

  while len(bin_num)<8:
    bin_num.append(0)

  for i in range(7,-1,-1):
    num.append(bin_num[i])

  swapped=[]
  for i in range(-4,4,1):
    swapped.append(num[i])
  print(str(swapped))

  value=0
  x=7
  for i in range(len(swapped)):
    value=value+(2**x)*swapped[i]
    x-=1
  print(value)

print("Enter the integer value:")
N=int(input())
swap_nibbles(N)