# -*- coding: utf-8 -*-
"""Boring_Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldRHcIa3GNV0hojIyTfKmi8PUOvY5EHc
"""

def boring_num_count(A,B):
  count=0
  for i in range(A,B+1):
    count=count+boring_number(i)
  
  print(count)

def boring_number(x):
  A=[]
  flag=1
  while(x>0):
    y=x%10
    A.append(y)
    x=x//10
  print(A)
  A.reverse()
  print(A)

  if len(A)%2!=0:
    A.append(0)

  for i in range(0,len(A),2):
    if A[i]%2==0 or A[i+1]%2!=0:
      flag=0
      break
  print(flag)
  return flag

boring_num_count(99,115)

