# -*- coding: utf-8 -*-
"""Count_2s(0_to_n).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crQl-HASLk4CvgNg2aQQw0_ElkOZ7J-1

Count the number of 2's between 0 to n.

Example:

*INPUT*:

n=22

*OUTPUT*:

6
"""

def num(n):
  sum=0
  for i in range(n+1):
    sum=sum+count(i)
    if count(i)>0:
      print(i)
  return sum

def count(a):
  count=0
  while a>0:
    c=a%10
    if c==2:
      count=count+1
    a=a//10
  return count

print("Enter the number: ")
n=int(input())
twos_present=num(n)
print(twos_present)