# -*- coding: utf-8 -*-
"""DynamicProg__NumberOfPaths.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iVAlPON71i2XQpuWtHJrLqlpyFgm29Pk

Count all the possible path from top left to bottom right of a MxN matrix.
From each cell you can move right or down.

Example 1:

*INPUT:*

3,3

*OUTPUT:*

6

Example 2:

*INPUT:*

2,8

*OUTPUT:*

8
"""

def ways(n,m):
  if n==1 or m==1:
    return 1
  else:
    return ways(n-1,m)+ways(n,m-1)

M=int(input("Enter M:"))
N=int(input("Enter N:"))
ways(M,N)