# -*- coding: utf-8 -*-
"""DynamicProg__EqualSum_Partition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R000IlvNgh2DoDRY_ZsEmb3VJ92h25Zz
"""

def subset(wt,W,n):
  t=[[-1 for x in range(W + 1)] for x in range(n + 1)]
  for i in range(n+1):
    for j in range(W+1):
      if i==0:
        t[i][j]=False
      if j==0:
        t[i][j]=True
  for i in range(1,n+1):
    for j in range(1,W+1):
      if wt[i-1]<=j:
        t[i][j]= t[i-1][j-wt[i-1]] or t[i-1][j]
      else:
        t[i][j]= t[i-1][j]
  print(t[n][W])

arr=[1,5,5,11]
n=len(arr)
sum=0
for i in range(n):
  sum=sum+arr[i]
if sum%2==0:
  subset(arr,sum//2,n)
else:
  print("False")