# -*- coding: utf-8 -*-
"""HashingMapping__FrequencyGame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqmdlz1SyuAmWuKigE_iWkmvcrL0qpHI

Frequency game:

Given an array A of size N(all positive). Find the largest number with minimum frequency.

Example 1:

*INPUT:*

2,2,5,50,1

*OUTPUT:*

50

Example 2:

*INPUT:*

2,2,5,50,1,55

*OUTPUT:*

55
"""

def countminfeq(A):
  #store the frequency values in dictionary
  D={}
  for i in range(len(A)):
    try:
      D[A[i]]+=1
    except:
      D[A[i]]=1

  #find the minimum frequency 
  min_freq=len(A) #higher bound: all elements are same
  for value in D.values():
    if value<min_freq:
      min_freq=value

  #find max element with min_freq
  max_ele=0
  for key in D.keys():
    if D[key]==min_freq and key>max_ele:
      max_ele=key
  
  print(max_ele)

print("Enter the list elements: ")
A=list(map(int,input().split(' ')))
countminfeq(A)