# -*- coding: utf-8 -*-
"""Hashing__CountPair_GivenSum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18i8sOW5g2SAW3oSNGGABasIOIo09RCWc

Count pairs with given sum. Given array of integers and k, find the count of pairs of elements in the array whose sum is equal to k.

Example 1:

*INPUT:*

n=4

k=6

A=[1,5,7,1]

*OUTPUT:*

2

Example 2:

*INPUT:*

n=4

k=2

A=[1,1,1,1]

*OUTPUT:*

6
"""

def pair_sum(A,k):
  count=0
  for i in range(len(A)-1):
    for j in range(i+1,len(A)):
      if A[i]+A[j]==k:
        count+=1
  print(count)

def pair_sum1(A,k):
  count=0
  m=[0]*1000
  for i in range(len(A)):
    m[A[i]]+=1
  for i in range(len(A)):
    if 2*A[i]==k:
      count+=m[k-A[i]]-1
    else:
      count+=m[k-A[i]]
  print(count)

def pair_sum2(A,k):
  D={}
  count=0
  for ele in A:
    try:
      D[ele]+=1
    except:
      D[ele]=1
  for i in range(len(A)):
    if ((k-A[i]) in D.keys() and k-A[i]!=A[i]):
      count+=D[ele]
      D[ele]-=1
    elif ((k-A[i]) in D.keys() and k-A[i]==A[i]):
      count+=D[ele]-1
      D[ele]-=1
  print(count)

print("Enter the array elements: ")
A=list(map(int,input().split(' ')))
print("Enter the k value: ")
k=int(input())
pair_sum2(A,k)