# -*- coding: utf-8 -*-
"""HashingMapping__Nuts&Bolts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19wUKbTvOGpj8artbOJ7SFkscQV7evVqw

Nuts and Bolts.

Do one to one mapping between nuts and bolts. Comparison of nut to nut and bot to bot is not allowed.


Example 1:

*INPUT:*

A=@,%,$,#,^

B=%,@,#,$,^

*OUTPUT:*

A=#,$,%,@,^

B=#,$,%,@,^

Example 2:

*INPUT:*

A=^,&,%,@,#,*,$,~,!

B=~,#,@,%,&,*,$,^,!

*OUTPUT:*

A=!,#,$,%,&,*,@,^,~

B=!,#,$,%,&,*,@,^,~
"""

def nuts_bolts(A,B):
  D1={}
  for ele in range(len(A)):
    try:
      D1[A[ele]]+=1
    except:
      D1[A[ele]]=1
  for i in range(len(B)):
    if B[i] in D1.keys():
      A[i]=B[i]
  if A==B:
    print(A)
    print(B)

print("Enter the two array elements:")
A=list((input().split(' ')))
B=list((input().split(' ')))
nuts_bolts(A,B)