# -*- coding: utf-8 -*-
"""HashingMapping__CountFrequency.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tT-ytaVp_uZR50V9CDhl20OZ-GFJlfSt

Given vector of N positive integers. Find the frequency of X.

Example:

*INPUT:*

A=[1,1,1,1,1]

X=1

*OUTPUT:*

5
"""

def countfeq(A,X):
  D={}
  for i in range(len(A)):
    try:
      D[A[i]]+=1
    except:
      D[A[i]]=1
  if X in D.keys():
    print(D[X])
  else:
    print("Key is not present")

print("Enter the list elements: ")
A=list(map(int,input().split(' ')))
X=int(input("Enter key: "))
countfeq(A,X)