# -*- coding: utf-8 -*-
"""LinkedList__RemoveLoop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wB9pFpDZWBBF2eHbR0xsKeB9E-933SQu

Remove loop in Linked List, if any.

Cis the position of node which is connected to the last node. If '0' there is no loop present.

Example 1:

*INPUT:*

N=3

Val={1,3,4}

C=2

*OUTPUT:*

1

Example 2:

*INPUT:*

N=4

Val={1,8,3,4}

C=0

*OUTPUT:*

1,8,3,4
"""

class Node:
  def __init__(self,data):
    self.data=data
    self.reference=None
class LinkedList:
  def __init__(self):
    self.head=None
  def traverse(self):
    presentNode=self.head
    if presentNode==None:
      print("Linked list is empty")
    else:
      while (presentNode):
        print("Data: ",presentNode.data)
        presentNode=presentNode.reference
  def insert_end(self,data):
    print("--------INSERTING NODE AT THE END---------")
    presentNode=self.head
    new_data=Node(data)
    if (presentNode==None):
      self.head=new_data
    else:
      while (presentNode.reference!=None):
        presentNode=presentNode.reference
      presentNode.reference=new_data

  def removeLoop(self,C):
    count=0
    presentNode=self.head
    if (presentNode==None):
      print("Linked list is already empty")
    elif (presentNode.reference==None and C==1):
      del_node=presentNode
      del del_node
      self.head=None
    else:
      while (count<C-2):
        count+=1
        presentNode=presentNode.reference
      del_node=presentNode.reference
      presentNode.reference=None
      while (del_node):
        del_node_next=del_node.reference
        del (del_node)
        del_node=del_node_next
    return self.head

LL1=LinkedList()
LL1.head=None
print("Enter the number of nodes: ")
N=int(input())
print("Enter the data for Linked list: ")
for i in range(N):
  LL1.insert_end(int(input()))
print("Entered Linked List is: ")
LL1.traverse()
C=int(input("Enter C: "))
if C==0:
  print("Linked list after removing loop: ")
  LL1.traverse()
else:
  LL1.removeLoop(C)
  print("Linked list after removing loop: ")
  LL1.traverse()