# -*- coding: utf-8 -*-
"""Pattern_Jumping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-R7Zuhp_IgOnMhGmHIqkg316v11zN8L

Pattern Jumping.

Akki starts at '0'. Jumps 1 unit in first go. If he is at a distance 'x' , next jump is 'x' units. Given N, find if akki can reach N.

Example 1:

*INPUT:*

N=1

*OUTPUT:*

True

Example 2:

*INPUT:*

N=7

*OUTPUT:*

False

Example 3:

*INPUT:*

N=64

*OUTPUT:*

True
"""

def jump_possible(N):
  if N==0 or N==1:
    return 'true'
  else:
    val=1
    while (val<=N):
      val+=val
      if val==N:
        return 'true'
  return 'false'

print("Enter the value of N: ")
N=int(input())
x=jump_possible(N)
print(x)