# -*- coding: utf-8 -*-
"""PowerOf2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZAgp_V2YgFaZKtOYxHZSmsA6SekNESj

Given N find if it can be represented in powers of two.

Example 1:

*INPUT:*

N=1

*OUTPUT:*

Yes

Example 2:

*INPUT:*

N=98

*OUTPUT:*

No
"""

import math

def check_power(N):
  if (math.ceil(math.log(N,2))==math.floor(math.log(N,2))):
    print("True")
  else:
    print("False")

N=int(input("Enter the integer: "))
check_power(N)