# -*- coding: utf-8 -*-
"""Pythagorean's_Triplet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_qW9V14LAjA8QMwJw7mSjmME5XD29xaj

Find Pythagorean's triplet:
a^2=b^2+c^2 in a given array.

Example:

*INPUT*:

[1,2,3,4,5]

*OUTPUT*:

[3,4,5]
"""

def triplets(A):
  n=len(A)
  for i in range(0,n):
    for j in range(0,n):
      for k in range(0,n):
        if ((A[i]**2) == (A[j]**2) + (A[k]**2) and A[j]>A[k]):
          print( "Found: ",A[i],A[j],A[k])

print("Enter the array elements")
A=list(map(int,input().split(' ')))
print(A)
triplets(A)