# -*- coding: utf-8 -*-
"""Recursion__Permutation_WithSpaces.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_vBz4zYAvL2THzvuSIEry9U9sBY59hi
"""

def per_space(I,O):
  if len(I)==0:
    print(O)
    return
  O1=''
  O2=''
  for i in O:
    O1+=i
    O2+=i
  O1+=' '
  O1+=I[0] 
  O2+=I[0] 
  #print(O2)

  IN=''
  for i in range(1,len(I)):
    IN = IN + I[i]
  per_space(IN,O1)
  per_space(IN,O2)

per_space('bc','a') #abc