# -*- coding: utf-8 -*-
"""Recursion__Factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3CF-LGaZPr4it-VngUx91A5K3jT0lOE

Given a positive integer, N. Find the factorial of N.
 

Example 1:

Input:

N = 5

Output:

120

Explanation:

5*4*3*2*1 = 120

Example 2:

Input:

N = 4

Output:

24

Explanation:

4*3*2*1 = 24
"""

def fact(n):
  if n==1:
    return 1
  return (n*fact(n-1))

x=fact(4)
x