# -*- coding: utf-8 -*-
"""Recursion__Balanced_Parenthesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbcaBjMRqcEiQl4Hvex5bm_X-PsgjdQo
"""

Out=[]
def Parenthesis(open,close,O):
  global Out
  if open==0 and close==0:
    Out.append(O)
    return
  if open!=0:
    O1=''
    for i in O:
      O1+=i
    O1+=('(')
    Parenthesis(open-1,close,O1)
  if close>open:
    O2=''
    for i in O:
      O2+=i
    O2+=(')')
    Parenthesis(open,close-1,O2)

Parenthesis(3,3,"")
Out