# -*- coding: utf-8 -*-
"""Recursion__Sort_Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-fAc_sFM9dJPFGotbLOGJCPhDBipodw
"""

def sort(A):
  if len(A)==1:
    return
  temp=A[len(A)-1]
  A.pop()
  print(A)
  sort(A)
  return insert(A,temp)

def insert(A,temp):
  if len(A)==0 or temp>=A[len(A)-1]:
    return A.append(temp)
  else:
    val=A[len(A)-1]
    A.pop()
    print(A,temp)
    insert(A,temp)
    return A.append(val)

A=[2,3,7,6,4,5,9]
sort(A)

A