# -*- coding: utf-8 -*-
"""Recursion__PowerSet_Subsets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NxL7C5T-R9G3BwRbRvzle0CxfInYec3Y
"""

def subset(I,O):
  #print(I,O)
  #print(len(I))
  #print("-----O={}------".format(O))
  if len(I)==0:
    print(O)
    return
  O1=''
  O2=''
  for i in O:
    O1+=i
    O2+=i
  O2+=I[0] 
  #print(O2)

  IN=''
  for i in range(1,len(I)):
    IN = IN + I[i]
  subset(IN,O1)
  subset(IN,O2)

subset('ab',' ')