# -*- coding: utf-8 -*-
"""Recursion__FindingPosition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ASheIpwOt-8uLNHv1QREm2-_6-5TV-vo
"""

def jose_alt(N,k):
  #form an array of N elements
  A=[]
  #According to zero indexing k--
  k=k-1
  for i in range(N,0,-1):
    A.append(i)
  print("A={}".format(A))
  A.pop(0)
  find_one(A,k,0,-1)

def find_one(A,k,index,ans):
  if len(A)==1:
    ans=A[0]
    print("Ans:{}".format(A))
    return
  else:
    index=(index+k) % len(A)
    print("Index={}".format(index))
    A.pop(index)
    print("A={}".format(A))
    find_one(A,k,index,ans)

N=int(input("Enter N:"))
jose_alt(N,2)