# -*- coding: utf-8 -*-
"""Recursion__N-Bit_1s_greater_0s.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bm8URg5GD8Z-6UP4e_kpAGoPDU96oJuw
"""

def solve(one,zero,n,op):
  if n==0:
    print(op)
    return
  O1=''
  O2=''
  for i in op:
    O1+=i
    O2+=i
  O1+='1' 
  solve(one+1,zero,n-1,O1)

  if one>zero:
    O2+='0'
    solve(one,zero+1,n-1,O2)
  return

solve(0,0,3,'')