# -*- coding: utf-8 -*-
"""Recursion_UniqueSubset_LexicographicallySorted.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDfZaEQpBbFsgI20UoesCUmfSN8iNHcn
"""

def unique_subset(I,O,Out):
  if len(I)==0:
    Out.append(O)
    print(Out)    #With Duplicates
    print(set(Out))   #Unique
    Out=(list(set(Out)))
    Out.sort()
    print(Out)    #lexicographically
    return Out
  O1=''
  O2=''
  for i in O:
    O1+=i
    O2+=i
  O2+=I[0] 
  #print(O2)

  IN=''
  for i in range(1,len(I)):
    IN = IN + I[i]
  unique_subset(IN,O1,Out)
  unique_subset(IN,O2,Out)

Out=[]
A=unique_subset('aab',' ',Out)
A