# -*- coding: utf-8 -*-
"""Recursion__PrintPattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1juOrliMHHKv_OuUsuitdgKcCmhhhcRiL

Print Pattern.

Print a sequence of numbers starting with N, without using loop, in which  A[i+1] = A[i] - 5,  if  A[i]>0, else A[i+1]=A[i] + 5  repeat it until A[i]=N.

Example 1:

*INPUT:*

N=16

*OUTPUT:*

16,11,6,1,-4,1,6,11,16

Example 2:

*INPUT:*

N=10

*OUTPUT:*

10,5,0,5,10
"""

def pattern(N,A,count,i,inc):
  if count==2:
    print("A:{}".format(A))
    return 0
  else:
    if A[i]>0 and inc==0:
      A.append(A[i]-5)
      print(A)
    elif A[i]<=0 or inc==1:
      A.append(A[i]+5)
      inc=1
      print(A)
    i=i+1
    if A[-1]==N:
      count+=1
    pattern(N,A,count,i,inc)

N=int(input("Enter N:"))
A=[]
A.append(N)
pattern(N,A,1,0,0)