# -*- coding: utf-8 -*-
"""Recursion__KthSymbol_Grammar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aiPyL5pJx9gNd5hidqlgh71NJfy53gIN
"""

def solve(n,k):
  if n==1 and k==1:
    return 0
  mid=(2**(n-1))//2
  if k<=mid:
    return solve(n-1,k)
  else:
    return not (solve(n-1,k-mid))

solve(4,7)