# -*- coding: utf-8 -*-
"""Replace_Zeros_by_5s.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XHOuar-33hJ0CCRNAoLkyxN6Gl68EY9l

Replace all zeros with 5's in a given integer.

Example 1:

*INPUT*:

n=1005

*OUTPUT*:

1555

Example 2:

*INPUT*:

n=145

*OUTPUT*:

145
"""

def replace_zeroes(n):
  out=[]
  while (n>0):
    a=n%10
    if (a==0):
      out.append('5')
    else:
      out.append(a)
    n=n//10
  out.reverse()
  print(*out, sep='')

print("Enter the number: ")
n=int(input())
replace_zeroes(n)