# -*- coding: utf-8 -*-
"""Stack__Stock_Span.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PyjyZmtpyIHe2K_BfjU5m-7QC68_hWUU

The stock span problem is a financial problem where we have a series of n daily price quotes for a stock and we need to calculate the span of stock’s price for all n days. 
The span Si of the stock’s price on a given day i is defined as the maximum number of consecutive days just before the given day, for which the price of the stock on the current day is less than or equal to its price on the given day.

For example, if an array of 7 days prices is given as {100, 80, 60, 70, 60, 75, 85}, then the span values for corresponding 7 days are {1, 1, 1, 2, 1, 4, 6}.

Input:

The first line of input contains an integer T denoting the number of test cases. The first line of each test case is N, N is the size of the array. The second line of each test case contains N input C[i].

Output:

For each testcase, print the span values for all days.

Constraints:

1 ≤ T ≤ 100
1 ≤ N ≤ 200
1 ≤ C[i] ≤ 800

Example:

Input:

2

7

100 80 60 70 60 75 85

6

10 4 5 90 120 80

Output:

1 1 1 2 1 4 6

1 1 2 4 5 1
"""

class Stack:
  def __init__(self,n):
    self.stack=[]
    self.index=[]
    self.size=n

  def push(self,element,index):
    if (len(self.stack) == self.size):
      print("STACK IS FULL")
    else:
      self.stack.append(element)
      self.index.append(index)

  def pop(self):
    if (len(self.stack) == 0):  #or self.stack==[]
      #print("STACK IS EMPTY")
      return -1
    else:
      self.stack.pop()
      self.index.pop()
      return 0
  
  def size_stack(self):
    size=len(self.stack)
    return size

  def isempty(self):
    x=self.size
    if x==0:
      print("Stack is empty")
      return 1
    else:
      print("Not empty")
      return 0

  def top(self):
    if len(self.stack)>0:
      #print (len(self.stack))
      A=[]
      A.append(self.stack[len(self.stack)-1]) 
      A.append(self.index[len(self.stack)-1])
      return A
    else:
      return -1

def stock_span(A):
  out_arr=[]
  out_index=[]
  s=Stack(len(A))
  for i in range(len(A)):
    if s.size_stack()==0:
      out_arr.append(-1)
      out_index.append(-1)
    elif s.size_stack()>0 and s.top()[0]>A[i]:
      out_arr.append(s.top()[0])
      out_index.append(i-1)
    elif s.size_stack()>0 and s.top()[0]<A[i]:
      while (s.size_stack()>0):
        if (s.top()[0]<A[i]):
          s.pop()
          #print(s.size_stack())
        else:
          break
      if s.size_stack()==0:
        out_arr.append(-1)
      else:
        out_arr.append(s.top()[0])
      out_index.append(s.top()[1])
    s.push(A[i],i)
  #out_arr.reverse()
  print(out_arr)
  print(out_index)
  for i in range(len(out_index)):
    out_index[i]=i-out_index[i]
  print(out_index)

A=[100,80,60,70,60,75,85]
#A.reverse()
print(A)
stock_span(A)