# -*- coding: utf-8 -*-
"""Stack__UsingArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQhHvAwB3X3NQdJ40cfrp7uCPnklQW7F

Implement stack using array.

Example 1:

*INPUT:*

push(2)

push(3)

pop()

push(4)

pop()

*OUTPUT:*

3,4

Example 2:

*INPUT:*

pop()

push(4)

push(5)

pop()

*OUTPUT:*

-1,5
"""

class stack_using_array:
  def __init__(self,n):
    self.stack=[]
    self.size=n
  def push(self,ele):
    if len(self.stack)==self.size:
      print("Stack Full")
      return
    else:
      self.stack.append(ele)
  def pop(self):
    if (len(self.stack)==0):
      print("-1")
    else:
      print(self.stack[-1])
      self.stack.pop()

S=stack_using_array(6)
S.push(2)
S.push(3)
S.pop()
S.push(4)
S.pop()