# -*- coding: utf-8 -*-
"""Strings__Permutation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3ykRn9mQlatouJ0DLI7688nGbnuYyhe

Given two strings write a method to decide if one is a permutation of other.

Example:

*INPUT*:

S1=abcdefg

S2=gec

*OUTPUT*:

Yes
"""

def check_per(A,B):
  count=0
  X=''
  if (len(A)<len(B)):
    X=A
    A=B
    B=X
  for i in A:    #focus on the syntax for strings
    for j in B:
      if i==j:
        count=count+1
        print(i)
  if count>=len(B):   #since for repeated elements count>len, e.g hello,lo: l is repeated and hence count=3>len(B)
    print("Yes")
  else:
    print("No")

str1= input("Enter the first string: ")
str2= input("Enter the second string: ")
check_per(str1,str2)