# -*- coding: utf-8 -*-
"""Strings__Permutation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3ykRn9mQlatouJ0DLI7688nGbnuYyhe

Given two strings write a method to decide if one is a permutation of other.

Example:

*INPUT*:

S1=abcdefg

S2=gec

*OUTPUT*:

Yes
"""

def check_permut(A,B):
  D={}
  count=0
  X=''
  if (len(A)<len(B)):
    X=A
    A=B
    B=X
  for ele in A:
    try:
      D[ele] +=1
    except:
      D[ele] = 1
  for ele in B:
    if D[ele]>=1:
      D[ele] -=1
    else:
      count=1
      break
  if count==1:
    print("No")
  else:
    print("Yes")

str1= input("Enter the first string: ")
str2= input("Enter the second string: ")
check_permut(str1,str2)