# -*- coding: utf-8 -*-
"""String__Repeated_ele.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GVigttqpfvGQQos_YWrmLg-fmVfYiC8D

Determine if a given string has all unique characters.

Example:

*INPUT*:

hello

*OUTPUT*:

No

Example:

*INPUT*:

planet

*OUTPUT*:

Yes
"""

def str_rep(A):
  c=0
  for i in range(len(A)-1):
    for j in range(i,len(A)):
      if A[i]==A[j]:
        c=1
        break
      
  if c==0:
    print("Yes")
  else:
    print("No")

A=input("Enter the string: ")
str_rep(A)