# -*- coding: utf-8 -*-
"""Strings__Compression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgQDRR8Mmo4BdmMA8odarK6j7Fd4fFlV

String Compression.

Example 1:

*INPUT:*

aabcccccaaa

*OUTPUT:*

a2bc5a3

Example 2:

*INPUT:*

compressed

*OUTPUT:*

compressed
"""

def str_compr(A):
  new_str=''
  new_str+=A[0]
  count=1
  i=1
  n=len(A)
  while (i<n):
    if A[i]==A[i-1]:
      count+=1
    elif (count>1):
      new_str+=str(count)
    else:
      count=1
      new_str+=A[i]
    if i==n-1:
      new_str+=str(count)
    i+=1

  if len(new_str)==len(A):
    print(A)
  else:
    print(new_str)

print("Enter The string: ")
A=input()
str_compr(A)