# -*- coding: utf-8 -*-
"""Strings__Remove_Duplicates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nCXa_WXP0pbXp46WvuUP73ah8Y4cvFUL

Remove all the duplicates from a given string.

Example:

*INPUT:*

HappyNewYear

*OUTPUT:*

HapyNewYr
"""

def remove_duplicates(A):
  new_str=''
  new_str += A[0]
  c=0
  for i in range(1,len(A)):
    c=0
    for j in range(i-1,-1,-1):
      if A[i]==A[j]:
        c=1
        print("Duplicate ",A[i])
    if c==0:
      new_str += A[i]
    print(new_str)

print("Enter the string:")
A=input()
remove_duplicates(A)