# -*- coding: utf-8 -*-
"""Strings__BinaryStr_SubStr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YgQs_CaXcVVhkLR5vgVL6ZZF7vE7WiGK

Binary String.

Count the substring which starts and ends with 1.

Example 1:

*INPUT:*

A=00100101

*OUTPUT:*

3

(1001,100101,101)

Example 2:

*INPUT:*

A=1111

*OUTPUT:*

6

(11,11,11,111,111,1111)

Example 3:

*INPUT:*

A=01101

*OUTPUT:*

3
"""

def count_substr(A):
  count=0
  n=len(A)
  for i in range(n-1):
    if (A[i]=='1'):     #NOTE: its a sting element**
      for j in range(i+1,n):
        if A[j]=='1':
          count=count+1
  print(count)

print("Enter the string: ")
A=input()
count_substr(A)