# -*- coding: utf-8 -*-
"""Strings__substitue_spaces.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cttxl7G0eItM2p0G3ke1PMhY0cI9rR3O

Substitute spaces between two words by "xyz".

Example:

*INPUT*:

A= Robert Brown

*OUTPUT*:

RobertxyzBrown
"""

def substitute_spaces(A,n):
  B=[]
  for i in range(n):
    if A[i]==' ':
      B.append("x")
      B.append("y")
      B.append("z")
    else:
      B.append(A[i])
  return(B)

def listToString(s):  
    # initialize an empty string 
    str1 = ""  
    # traverse in the string   
    for ele in s:  
        str1 += ele   
    # return string   
    return str1

print("Enter the array elements")
A=list((input()))
print(A)
n=len(A)
Res=substitute_spaces(A,n)
print(*Res)
listToString(Res)