# -*- coding: utf-8 -*-
"""Strings__LocateFirstOccrence(S,X).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cKDOPnossWNdIJLNlt6GCVZyBFnk-64v

Implement strstr. 

Function takes two arguments (S,X) and locates the first occurence of X in S.

Example 1:

*INPUT:*

S=xyzforxyzfor

X=fr

*OUTPUT:*

-1

Example 2:

*INPUT:*

S=xyzforxyz

X=for

*OUTPUT:*

3
"""

def strstr(S,X):
  i=0
  while (i<=len(S)-len(X)):
    count=0
    c=-1
    if S[i]==X[0]:
      count+=1
      c=i
      for j in range(1,len(X)):
        if S[i+j]==X[j]:
          count+=1
      if count==len(X):
        print(c)
        return
    i+=1

  print(c)
  return

print("Enter the two strings:")
S=input()
X=input()
strstr(S,X)