# -*- coding: utf-8 -*-
"""Strings__MinIndexChar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vonK8MfsuZIB6rdchJS4bSU7NUvEgtBT

Minimum Indexes character.

For strings S1,S2 find the character in S2 that is present at the minimum index of S1. If no charater is present print "No character found".

Example 1:

*INPUT:*

S1=hello

S2=set

*OUTPUT:*

e

Example 2:

*INPUT:*

S1=abcffet

S2=onkl

*OUTPUT:*

No character found
"""

def min_index(A,B):
  for i in range(len(A)):
    for j in range(len(B)):
      if A[i]==B[j]:
        return (A[i])
        break
  return "No Character found"

print("Enter the sting: ")
A=input()
B=input()
Res=min_index(A,B)
print(Res)